sudo:required
language: generic

services:
  - docker

before_install:
  - docker build -t meir192/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true meir192/react-test npm run test

after_success:
  - docker build -t meir192/multi-client ./client
  - docker build -t meir192/multi-nginx ./nginx
  - docker build -t meir192/multi-server ./server
  - docker build -t meir192/multi-worker ./worker
  # login to the docker CLI
  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --pasword-stdin
  # push images to docker hub
  - docker push meir192/multi-client
  - docker push meir192/multi-nginx
  - docker push meir192/multi-server
  - docker push meir192/multi-worker
